
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using DAL;

namespace BLL
{
	public class ReferenceImages : _ReferenceImages
	{
		public ReferenceImages()
		{
		
		}

        public virtual bool GetImagesByRefID(int refid)
        {
            this.Where.ReferenceID.Value = refid;
            this.Where.ReferenceID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            return this.Query.Load();
        }
	}
}
