
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using Flight_DAL;
namespace Flight_BLL
{
	public class ManualForm : _ManualForm
	{
		public ManualForm()
		{
		
		}
	}
}
