
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GlobalLogistics.DAL
{
	public abstract class _CompanyEnabledOptions : SqlClientEntity
	{
		public _CompanyEnabledOptions()
		{
			this.QuerySource = "CompanyEnabledOptions";
			this.MappingName = "CompanyEnabledOptions";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CompanyEnabledOptionsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int CompanyEnabledOptionID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.CompanyEnabledOptionID, CompanyEnabledOptionID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CompanyEnabledOptionsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter CompanyEnabledOptionID
			{
				get
				{
					return new SqlParameter("@CompanyEnabledOptionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter PackageOptionID
			{
				get
				{
					return new SqlParameter("@PackageOptionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter CompanyID
			{
				get
				{
					return new SqlParameter("@CompanyID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Enabled
			{
				get
				{
					return new SqlParameter("@Enabled", SqlDbType.Bit, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string CompanyEnabledOptionID = "CompanyEnabledOptionID";
            public const string PackageOptionID = "PackageOptionID";
            public const string CompanyID = "CompanyID";
            public const string Enabled = "Enabled";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CompanyEnabledOptionID] = _CompanyEnabledOptions.PropertyNames.CompanyEnabledOptionID;
					ht[PackageOptionID] = _CompanyEnabledOptions.PropertyNames.PackageOptionID;
					ht[CompanyID] = _CompanyEnabledOptions.PropertyNames.CompanyID;
					ht[Enabled] = _CompanyEnabledOptions.PropertyNames.Enabled;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string CompanyEnabledOptionID = "CompanyEnabledOptionID";
            public const string PackageOptionID = "PackageOptionID";
            public const string CompanyID = "CompanyID";
            public const string Enabled = "Enabled";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CompanyEnabledOptionID] = _CompanyEnabledOptions.ColumnNames.CompanyEnabledOptionID;
					ht[PackageOptionID] = _CompanyEnabledOptions.ColumnNames.PackageOptionID;
					ht[CompanyID] = _CompanyEnabledOptions.ColumnNames.CompanyID;
					ht[Enabled] = _CompanyEnabledOptions.ColumnNames.Enabled;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string CompanyEnabledOptionID = "s_CompanyEnabledOptionID";
            public const string PackageOptionID = "s_PackageOptionID";
            public const string CompanyID = "s_CompanyID";
            public const string Enabled = "s_Enabled";

		}
		#endregion		
		
		#region Properties
	
		public virtual int CompanyEnabledOptionID
	    {
			get
	        {
				return base.Getint(ColumnNames.CompanyEnabledOptionID);
			}
			set
	        {
				base.Setint(ColumnNames.CompanyEnabledOptionID, value);
			}
		}

		public virtual int PackageOptionID
	    {
			get
	        {
				return base.Getint(ColumnNames.PackageOptionID);
			}
			set
	        {
				base.Setint(ColumnNames.PackageOptionID, value);
			}
		}

		public virtual int CompanyID
	    {
			get
	        {
				return base.Getint(ColumnNames.CompanyID);
			}
			set
	        {
				base.Setint(ColumnNames.CompanyID, value);
			}
		}

		public virtual bool Enabled
	    {
			get
	        {
				return base.Getbool(ColumnNames.Enabled);
			}
			set
	        {
				base.Setbool(ColumnNames.Enabled, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_CompanyEnabledOptionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CompanyEnabledOptionID) ? string.Empty : base.GetintAsString(ColumnNames.CompanyEnabledOptionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CompanyEnabledOptionID);
				else
					this.CompanyEnabledOptionID = base.SetintAsString(ColumnNames.CompanyEnabledOptionID, value);
			}
		}

		public virtual string s_PackageOptionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PackageOptionID) ? string.Empty : base.GetintAsString(ColumnNames.PackageOptionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PackageOptionID);
				else
					this.PackageOptionID = base.SetintAsString(ColumnNames.PackageOptionID, value);
			}
		}

		public virtual string s_CompanyID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CompanyID) ? string.Empty : base.GetintAsString(ColumnNames.CompanyID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CompanyID);
				else
					this.CompanyID = base.SetintAsString(ColumnNames.CompanyID, value);
			}
		}

		public virtual string s_Enabled
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Enabled) ? string.Empty : base.GetboolAsString(ColumnNames.Enabled);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Enabled);
				else
					this.Enabled = base.SetboolAsString(ColumnNames.Enabled, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter CompanyEnabledOptionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CompanyEnabledOptionID, Parameters.CompanyEnabledOptionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PackageOptionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PackageOptionID, Parameters.PackageOptionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CompanyID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CompanyID, Parameters.CompanyID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Enabled
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Enabled, Parameters.Enabled);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter CompanyEnabledOptionID
		    {
				get
		        {
					if(_CompanyEnabledOptionID_W == null)
	        	    {
						_CompanyEnabledOptionID_W = TearOff.CompanyEnabledOptionID;
					}
					return _CompanyEnabledOptionID_W;
				}
			}

			public WhereParameter PackageOptionID
		    {
				get
		        {
					if(_PackageOptionID_W == null)
	        	    {
						_PackageOptionID_W = TearOff.PackageOptionID;
					}
					return _PackageOptionID_W;
				}
			}

			public WhereParameter CompanyID
		    {
				get
		        {
					if(_CompanyID_W == null)
	        	    {
						_CompanyID_W = TearOff.CompanyID;
					}
					return _CompanyID_W;
				}
			}

			public WhereParameter Enabled
		    {
				get
		        {
					if(_Enabled_W == null)
	        	    {
						_Enabled_W = TearOff.Enabled;
					}
					return _Enabled_W;
				}
			}

			private WhereParameter _CompanyEnabledOptionID_W = null;
			private WhereParameter _PackageOptionID_W = null;
			private WhereParameter _CompanyID_W = null;
			private WhereParameter _Enabled_W = null;

			public void WhereClauseReset()
			{
				_CompanyEnabledOptionID_W = null;
				_PackageOptionID_W = null;
				_CompanyID_W = null;
				_Enabled_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter CompanyEnabledOptionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CompanyEnabledOptionID, Parameters.CompanyEnabledOptionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PackageOptionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PackageOptionID, Parameters.PackageOptionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CompanyID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CompanyID, Parameters.CompanyID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Enabled
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Enabled, Parameters.Enabled);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter CompanyEnabledOptionID
		    {
				get
		        {
					if(_CompanyEnabledOptionID_W == null)
	        	    {
						_CompanyEnabledOptionID_W = TearOff.CompanyEnabledOptionID;
					}
					return _CompanyEnabledOptionID_W;
				}
			}

			public AggregateParameter PackageOptionID
		    {
				get
		        {
					if(_PackageOptionID_W == null)
	        	    {
						_PackageOptionID_W = TearOff.PackageOptionID;
					}
					return _PackageOptionID_W;
				}
			}

			public AggregateParameter CompanyID
		    {
				get
		        {
					if(_CompanyID_W == null)
	        	    {
						_CompanyID_W = TearOff.CompanyID;
					}
					return _CompanyID_W;
				}
			}

			public AggregateParameter Enabled
		    {
				get
		        {
					if(_Enabled_W == null)
	        	    {
						_Enabled_W = TearOff.Enabled;
					}
					return _Enabled_W;
				}
			}

			private AggregateParameter _CompanyEnabledOptionID_W = null;
			private AggregateParameter _PackageOptionID_W = null;
			private AggregateParameter _CompanyID_W = null;
			private AggregateParameter _Enabled_W = null;

			public void AggregateClauseReset()
			{
				_CompanyEnabledOptionID_W = null;
				_PackageOptionID_W = null;
				_CompanyID_W = null;
				_Enabled_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CompanyEnabledOptionsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.CompanyEnabledOptionID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CompanyEnabledOptionsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CompanyEnabledOptionsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.CompanyEnabledOptionID);
			p.SourceColumn = ColumnNames.CompanyEnabledOptionID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.CompanyEnabledOptionID);
			p.SourceColumn = ColumnNames.CompanyEnabledOptionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PackageOptionID);
			p.SourceColumn = ColumnNames.PackageOptionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CompanyID);
			p.SourceColumn = ColumnNames.CompanyID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Enabled);
			p.SourceColumn = ColumnNames.Enabled;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
