<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:Port_0="http://cso.citc" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://cso.citc/Binding" name="Export1_CsoCheckPrsHttp_Service" targetNamespace="http://cso.citc/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://cso.citc" location="CsoCheckPrs.wsdl" />
  <wsdl:types />
  <wsdl:binding name="Export1_CsoCheckPrsHttpBinding" type="Port_0:CsoCheckPrs">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="csogetPersonDetByapfn">
      <soap:operation soapAction="" />
      <wsdl:input name="csogetPersonDetByapfnRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="csogetPersonDetByapfnResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="csogetPersonDetByIdnum">
      <soap:operation soapAction="" />
      <wsdl:input name="csogetPersonDetByIdnumRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="csogetPersonDetByIdnumResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="csogetPersonDetByFcn">
      <soap:operation soapAction="" />
      <wsdl:input name="csogetPersonDetByFcnRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="csogetPersonDetByFcnResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Export1_CsoCheckPrsHttpService">
    <wsdl:port name="Export1_CsoCheckPrsHttpPort" binding="this:Export1_CsoCheckPrsHttpBinding">
      <soap:address location="https://10.29.6.105/CSOServiceMediationWeb/sca/Export1" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>