
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using View;
using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;// We should use the namespace of Data access layer generated form business entity

namespace Pricing.BLL
{
	public class v_StatusHistory : _v_StatusHistory
	{
        public v_StatusHistory()
		{
		
		}

        public void LoadStatusForTrade(int _tradePricingID)
        {
            this.Where.TradePricingID.Value = _tradePricingID;
            this.Where.TradePricingID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;

            this.Query.AddOrderBy(v_StatusHistory.ColumnNames.StatusDate, MyGeneration.dOOdads.WhereParameter.Dir.DESC);

            this.Query.Load();
        }

        

       
	}
}
