
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace WhiteChat.DAL
{
	public abstract class _ChatRoom : SqlClientEntity
	{
		public _ChatRoom()
		{
			this.QuerySource = "ChatRoom";
			this.MappingName = "ChatRoom";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_ChatRoomLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int ChatRoomID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ChatRoomID, ChatRoomID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_ChatRoomLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter ChatRoomID
			{
				get
				{
					return new SqlParameter("@ChatRoomID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter CategoryID
			{
				get
				{
					return new SqlParameter("@CategoryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter SubCategoryID
			{
				get
				{
					return new SqlParameter("@SubCategoryID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string ChatRoomID = "ChatRoomID";
            public const string Name = "Name";
            public const string CategoryID = "CategoryID";
            public const string SubCategoryID = "SubCategoryID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ChatRoomID] = _ChatRoom.PropertyNames.ChatRoomID;
					ht[Name] = _ChatRoom.PropertyNames.Name;
					ht[CategoryID] = _ChatRoom.PropertyNames.CategoryID;
					ht[SubCategoryID] = _ChatRoom.PropertyNames.SubCategoryID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string ChatRoomID = "ChatRoomID";
            public const string Name = "Name";
            public const string CategoryID = "CategoryID";
            public const string SubCategoryID = "SubCategoryID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ChatRoomID] = _ChatRoom.ColumnNames.ChatRoomID;
					ht[Name] = _ChatRoom.ColumnNames.Name;
					ht[CategoryID] = _ChatRoom.ColumnNames.CategoryID;
					ht[SubCategoryID] = _ChatRoom.ColumnNames.SubCategoryID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string ChatRoomID = "s_ChatRoomID";
            public const string Name = "s_Name";
            public const string CategoryID = "s_CategoryID";
            public const string SubCategoryID = "s_SubCategoryID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int ChatRoomID
	    {
			get
	        {
				return base.Getint(ColumnNames.ChatRoomID);
			}
			set
	        {
				base.Setint(ColumnNames.ChatRoomID, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual int CategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.CategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.CategoryID, value);
			}
		}

		public virtual int SubCategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.SubCategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.SubCategoryID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_ChatRoomID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ChatRoomID) ? string.Empty : base.GetintAsString(ColumnNames.ChatRoomID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ChatRoomID);
				else
					this.ChatRoomID = base.SetintAsString(ColumnNames.ChatRoomID, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_CategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryID) ? string.Empty : base.GetintAsString(ColumnNames.CategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryID);
				else
					this.CategoryID = base.SetintAsString(ColumnNames.CategoryID, value);
			}
		}

		public virtual string s_SubCategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SubCategoryID) ? string.Empty : base.GetintAsString(ColumnNames.SubCategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SubCategoryID);
				else
					this.SubCategoryID = base.SetintAsString(ColumnNames.SubCategoryID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ChatRoomID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ChatRoomID, Parameters.ChatRoomID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryID, Parameters.CategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SubCategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SubCategoryID, Parameters.SubCategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ChatRoomID
		    {
				get
		        {
					if(_ChatRoomID_W == null)
	        	    {
						_ChatRoomID_W = TearOff.ChatRoomID;
					}
					return _ChatRoomID_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public WhereParameter SubCategoryID
		    {
				get
		        {
					if(_SubCategoryID_W == null)
	        	    {
						_SubCategoryID_W = TearOff.SubCategoryID;
					}
					return _SubCategoryID_W;
				}
			}

			private WhereParameter _ChatRoomID_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _CategoryID_W = null;
			private WhereParameter _SubCategoryID_W = null;

			public void WhereClauseReset()
			{
				_ChatRoomID_W = null;
				_Name_W = null;
				_CategoryID_W = null;
				_SubCategoryID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ChatRoomID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ChatRoomID, Parameters.ChatRoomID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryID, Parameters.CategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SubCategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SubCategoryID, Parameters.SubCategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ChatRoomID
		    {
				get
		        {
					if(_ChatRoomID_W == null)
	        	    {
						_ChatRoomID_W = TearOff.ChatRoomID;
					}
					return _ChatRoomID_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public AggregateParameter SubCategoryID
		    {
				get
		        {
					if(_SubCategoryID_W == null)
	        	    {
						_SubCategoryID_W = TearOff.SubCategoryID;
					}
					return _SubCategoryID_W;
				}
			}

			private AggregateParameter _ChatRoomID_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _CategoryID_W = null;
			private AggregateParameter _SubCategoryID_W = null;

			public void AggregateClauseReset()
			{
				_ChatRoomID_W = null;
				_Name_W = null;
				_CategoryID_W = null;
				_SubCategoryID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ChatRoomInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.ChatRoomID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ChatRoomUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ChatRoomDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.ChatRoomID);
			p.SourceColumn = ColumnNames.ChatRoomID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.ChatRoomID);
			p.SourceColumn = ColumnNames.ChatRoomID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CategoryID);
			p.SourceColumn = ColumnNames.CategoryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SubCategoryID);
			p.SourceColumn = ColumnNames.SubCategoryID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
