
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace E3zmni.DAL
{
	public abstract class _Categories : SqlClientEntity
	{
		public _Categories()
		{
			this.QuerySource = "Categories";
			this.MappingName = "Categories";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CategoriesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int CategoryID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.CategoryID, CategoryID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CategoriesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter CategoryID
			{
				get
				{
					return new SqlParameter("@CategoryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter CatNameAr
			{
				get
				{
					return new SqlParameter("@CatNameAr", SqlDbType.NVarChar, 250);
				}
			}
			
			public static SqlParameter CatNameEng
			{
				get
				{
					return new SqlParameter("@CatNameEng", SqlDbType.NVarChar, 250);
				}
			}
			
			public static SqlParameter CatImage
			{
				get
				{
					return new SqlParameter("@CatImage", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter MainCatId
			{
				get
				{
					return new SqlParameter("@MainCatId", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter HoverImage
			{
				get
				{
					return new SqlParameter("@HoverImage", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter IsPartySupplier
			{
				get
				{
					return new SqlParameter("@IsPartySupplier", SqlDbType.Bit, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string CategoryID = "CategoryID";
            public const string CatNameAr = "CatNameAr";
            public const string CatNameEng = "CatNameEng";
            public const string CatImage = "CatImage";
            public const string MainCatId = "MainCatId";
            public const string HoverImage = "HoverImage";
            public const string IsPartySupplier = "IsPartySupplier";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CategoryID] = _Categories.PropertyNames.CategoryID;
					ht[CatNameAr] = _Categories.PropertyNames.CatNameAr;
					ht[CatNameEng] = _Categories.PropertyNames.CatNameEng;
					ht[CatImage] = _Categories.PropertyNames.CatImage;
					ht[MainCatId] = _Categories.PropertyNames.MainCatId;
					ht[HoverImage] = _Categories.PropertyNames.HoverImage;
					ht[IsPartySupplier] = _Categories.PropertyNames.IsPartySupplier;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string CategoryID = "CategoryID";
            public const string CatNameAr = "CatNameAr";
            public const string CatNameEng = "CatNameEng";
            public const string CatImage = "CatImage";
            public const string MainCatId = "MainCatId";
            public const string HoverImage = "HoverImage";
            public const string IsPartySupplier = "IsPartySupplier";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CategoryID] = _Categories.ColumnNames.CategoryID;
					ht[CatNameAr] = _Categories.ColumnNames.CatNameAr;
					ht[CatNameEng] = _Categories.ColumnNames.CatNameEng;
					ht[CatImage] = _Categories.ColumnNames.CatImage;
					ht[MainCatId] = _Categories.ColumnNames.MainCatId;
					ht[HoverImage] = _Categories.ColumnNames.HoverImage;
					ht[IsPartySupplier] = _Categories.ColumnNames.IsPartySupplier;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string CategoryID = "s_CategoryID";
            public const string CatNameAr = "s_CatNameAr";
            public const string CatNameEng = "s_CatNameEng";
            public const string CatImage = "s_CatImage";
            public const string MainCatId = "s_MainCatId";
            public const string HoverImage = "s_HoverImage";
            public const string IsPartySupplier = "s_IsPartySupplier";

		}
		#endregion		
		
		#region Properties
	
		public virtual int CategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.CategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.CategoryID, value);
			}
		}

		public virtual string CatNameAr
	    {
			get
	        {
				return base.Getstring(ColumnNames.CatNameAr);
			}
			set
	        {
				base.Setstring(ColumnNames.CatNameAr, value);
			}
		}

		public virtual string CatNameEng
	    {
			get
	        {
				return base.Getstring(ColumnNames.CatNameEng);
			}
			set
	        {
				base.Setstring(ColumnNames.CatNameEng, value);
			}
		}

		public virtual string CatImage
	    {
			get
	        {
				return base.Getstring(ColumnNames.CatImage);
			}
			set
	        {
				base.Setstring(ColumnNames.CatImage, value);
			}
		}

		public virtual int MainCatId
	    {
			get
	        {
				return base.Getint(ColumnNames.MainCatId);
			}
			set
	        {
				base.Setint(ColumnNames.MainCatId, value);
			}
		}

		public virtual string HoverImage
	    {
			get
	        {
				return base.Getstring(ColumnNames.HoverImage);
			}
			set
	        {
				base.Setstring(ColumnNames.HoverImage, value);
			}
		}

		public virtual bool IsPartySupplier
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsPartySupplier);
			}
			set
	        {
				base.Setbool(ColumnNames.IsPartySupplier, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_CategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryID) ? string.Empty : base.GetintAsString(ColumnNames.CategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryID);
				else
					this.CategoryID = base.SetintAsString(ColumnNames.CategoryID, value);
			}
		}

		public virtual string s_CatNameAr
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CatNameAr) ? string.Empty : base.GetstringAsString(ColumnNames.CatNameAr);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CatNameAr);
				else
					this.CatNameAr = base.SetstringAsString(ColumnNames.CatNameAr, value);
			}
		}

		public virtual string s_CatNameEng
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CatNameEng) ? string.Empty : base.GetstringAsString(ColumnNames.CatNameEng);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CatNameEng);
				else
					this.CatNameEng = base.SetstringAsString(ColumnNames.CatNameEng, value);
			}
		}

		public virtual string s_CatImage
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CatImage) ? string.Empty : base.GetstringAsString(ColumnNames.CatImage);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CatImage);
				else
					this.CatImage = base.SetstringAsString(ColumnNames.CatImage, value);
			}
		}

		public virtual string s_MainCatId
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MainCatId) ? string.Empty : base.GetintAsString(ColumnNames.MainCatId);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MainCatId);
				else
					this.MainCatId = base.SetintAsString(ColumnNames.MainCatId, value);
			}
		}

		public virtual string s_HoverImage
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.HoverImage) ? string.Empty : base.GetstringAsString(ColumnNames.HoverImage);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.HoverImage);
				else
					this.HoverImage = base.SetstringAsString(ColumnNames.HoverImage, value);
			}
		}

		public virtual string s_IsPartySupplier
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsPartySupplier) ? string.Empty : base.GetboolAsString(ColumnNames.IsPartySupplier);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsPartySupplier);
				else
					this.IsPartySupplier = base.SetboolAsString(ColumnNames.IsPartySupplier, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter CategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryID, Parameters.CategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CatNameAr
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CatNameAr, Parameters.CatNameAr);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CatNameEng
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CatNameEng, Parameters.CatNameEng);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CatImage
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CatImage, Parameters.CatImage);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MainCatId
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MainCatId, Parameters.MainCatId);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter HoverImage
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.HoverImage, Parameters.HoverImage);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsPartySupplier
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsPartySupplier, Parameters.IsPartySupplier);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public WhereParameter CatNameAr
		    {
				get
		        {
					if(_CatNameAr_W == null)
	        	    {
						_CatNameAr_W = TearOff.CatNameAr;
					}
					return _CatNameAr_W;
				}
			}

			public WhereParameter CatNameEng
		    {
				get
		        {
					if(_CatNameEng_W == null)
	        	    {
						_CatNameEng_W = TearOff.CatNameEng;
					}
					return _CatNameEng_W;
				}
			}

			public WhereParameter CatImage
		    {
				get
		        {
					if(_CatImage_W == null)
	        	    {
						_CatImage_W = TearOff.CatImage;
					}
					return _CatImage_W;
				}
			}

			public WhereParameter MainCatId
		    {
				get
		        {
					if(_MainCatId_W == null)
	        	    {
						_MainCatId_W = TearOff.MainCatId;
					}
					return _MainCatId_W;
				}
			}

			public WhereParameter HoverImage
		    {
				get
		        {
					if(_HoverImage_W == null)
	        	    {
						_HoverImage_W = TearOff.HoverImage;
					}
					return _HoverImage_W;
				}
			}

			public WhereParameter IsPartySupplier
		    {
				get
		        {
					if(_IsPartySupplier_W == null)
	        	    {
						_IsPartySupplier_W = TearOff.IsPartySupplier;
					}
					return _IsPartySupplier_W;
				}
			}

			private WhereParameter _CategoryID_W = null;
			private WhereParameter _CatNameAr_W = null;
			private WhereParameter _CatNameEng_W = null;
			private WhereParameter _CatImage_W = null;
			private WhereParameter _MainCatId_W = null;
			private WhereParameter _HoverImage_W = null;
			private WhereParameter _IsPartySupplier_W = null;

			public void WhereClauseReset()
			{
				_CategoryID_W = null;
				_CatNameAr_W = null;
				_CatNameEng_W = null;
				_CatImage_W = null;
				_MainCatId_W = null;
				_HoverImage_W = null;
				_IsPartySupplier_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter CategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryID, Parameters.CategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CatNameAr
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CatNameAr, Parameters.CatNameAr);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CatNameEng
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CatNameEng, Parameters.CatNameEng);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CatImage
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CatImage, Parameters.CatImage);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MainCatId
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MainCatId, Parameters.MainCatId);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter HoverImage
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.HoverImage, Parameters.HoverImage);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsPartySupplier
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsPartySupplier, Parameters.IsPartySupplier);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public AggregateParameter CatNameAr
		    {
				get
		        {
					if(_CatNameAr_W == null)
	        	    {
						_CatNameAr_W = TearOff.CatNameAr;
					}
					return _CatNameAr_W;
				}
			}

			public AggregateParameter CatNameEng
		    {
				get
		        {
					if(_CatNameEng_W == null)
	        	    {
						_CatNameEng_W = TearOff.CatNameEng;
					}
					return _CatNameEng_W;
				}
			}

			public AggregateParameter CatImage
		    {
				get
		        {
					if(_CatImage_W == null)
	        	    {
						_CatImage_W = TearOff.CatImage;
					}
					return _CatImage_W;
				}
			}

			public AggregateParameter MainCatId
		    {
				get
		        {
					if(_MainCatId_W == null)
	        	    {
						_MainCatId_W = TearOff.MainCatId;
					}
					return _MainCatId_W;
				}
			}

			public AggregateParameter HoverImage
		    {
				get
		        {
					if(_HoverImage_W == null)
	        	    {
						_HoverImage_W = TearOff.HoverImage;
					}
					return _HoverImage_W;
				}
			}

			public AggregateParameter IsPartySupplier
		    {
				get
		        {
					if(_IsPartySupplier_W == null)
	        	    {
						_IsPartySupplier_W = TearOff.IsPartySupplier;
					}
					return _IsPartySupplier_W;
				}
			}

			private AggregateParameter _CategoryID_W = null;
			private AggregateParameter _CatNameAr_W = null;
			private AggregateParameter _CatNameEng_W = null;
			private AggregateParameter _CatImage_W = null;
			private AggregateParameter _MainCatId_W = null;
			private AggregateParameter _HoverImage_W = null;
			private AggregateParameter _IsPartySupplier_W = null;

			public void AggregateClauseReset()
			{
				_CategoryID_W = null;
				_CatNameAr_W = null;
				_CatNameEng_W = null;
				_CatImage_W = null;
				_MainCatId_W = null;
				_HoverImage_W = null;
				_IsPartySupplier_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CategoriesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.CategoryID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CategoriesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CategoriesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.CategoryID);
			p.SourceColumn = ColumnNames.CategoryID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.CategoryID);
			p.SourceColumn = ColumnNames.CategoryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CatNameAr);
			p.SourceColumn = ColumnNames.CatNameAr;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CatNameEng);
			p.SourceColumn = ColumnNames.CatNameEng;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CatImage);
			p.SourceColumn = ColumnNames.CatImage;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MainCatId);
			p.SourceColumn = ColumnNames.MainCatId;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.HoverImage);
			p.SourceColumn = ColumnNames.HoverImage;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsPartySupplier);
			p.SourceColumn = ColumnNames.IsPartySupplier;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
