
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace E3zmni.DAL
{
	public abstract class _TopLevelCat : SqlClientEntity
	{
		public _TopLevelCat()
		{
			this.QuerySource = "TopLevelCat";
			this.MappingName = "TopLevelCat";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_TopLevelCatLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int TopLevelCatID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.TopLevelCatID, TopLevelCatID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_TopLevelCatLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter TopLevelCatID
			{
				get
				{
					return new SqlParameter("@TopLevelCatID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter NameEng
			{
				get
				{
					return new SqlParameter("@NameEng", SqlDbType.NVarChar, 30);
				}
			}
			
			public static SqlParameter NameAr
			{
				get
				{
					return new SqlParameter("@NameAr", SqlDbType.NVarChar, 30);
				}
			}
			
			public static SqlParameter ImagePath
			{
				get
				{
					return new SqlParameter("@ImagePath", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter HoverImage
			{
				get
				{
					return new SqlParameter("@HoverImage", SqlDbType.NVarChar, 200);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string TopLevelCatID = "TopLevelCatID";
            public const string NameEng = "NameEng";
            public const string NameAr = "NameAr";
            public const string ImagePath = "ImagePath";
            public const string HoverImage = "HoverImage";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[TopLevelCatID] = _TopLevelCat.PropertyNames.TopLevelCatID;
					ht[NameEng] = _TopLevelCat.PropertyNames.NameEng;
					ht[NameAr] = _TopLevelCat.PropertyNames.NameAr;
					ht[ImagePath] = _TopLevelCat.PropertyNames.ImagePath;
					ht[HoverImage] = _TopLevelCat.PropertyNames.HoverImage;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string TopLevelCatID = "TopLevelCatID";
            public const string NameEng = "NameEng";
            public const string NameAr = "NameAr";
            public const string ImagePath = "ImagePath";
            public const string HoverImage = "HoverImage";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[TopLevelCatID] = _TopLevelCat.ColumnNames.TopLevelCatID;
					ht[NameEng] = _TopLevelCat.ColumnNames.NameEng;
					ht[NameAr] = _TopLevelCat.ColumnNames.NameAr;
					ht[ImagePath] = _TopLevelCat.ColumnNames.ImagePath;
					ht[HoverImage] = _TopLevelCat.ColumnNames.HoverImage;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string TopLevelCatID = "s_TopLevelCatID";
            public const string NameEng = "s_NameEng";
            public const string NameAr = "s_NameAr";
            public const string ImagePath = "s_ImagePath";
            public const string HoverImage = "s_HoverImage";

		}
		#endregion		
		
		#region Properties
	
		public virtual int TopLevelCatID
	    {
			get
	        {
				return base.Getint(ColumnNames.TopLevelCatID);
			}
			set
	        {
				base.Setint(ColumnNames.TopLevelCatID, value);
			}
		}

		public virtual string NameEng
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameEng);
			}
			set
	        {
				base.Setstring(ColumnNames.NameEng, value);
			}
		}

		public virtual string NameAr
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameAr);
			}
			set
	        {
				base.Setstring(ColumnNames.NameAr, value);
			}
		}

		public virtual string ImagePath
	    {
			get
	        {
				return base.Getstring(ColumnNames.ImagePath);
			}
			set
	        {
				base.Setstring(ColumnNames.ImagePath, value);
			}
		}

		public virtual string HoverImage
	    {
			get
	        {
				return base.Getstring(ColumnNames.HoverImage);
			}
			set
	        {
				base.Setstring(ColumnNames.HoverImage, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_TopLevelCatID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TopLevelCatID) ? string.Empty : base.GetintAsString(ColumnNames.TopLevelCatID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TopLevelCatID);
				else
					this.TopLevelCatID = base.SetintAsString(ColumnNames.TopLevelCatID, value);
			}
		}

		public virtual string s_NameEng
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameEng) ? string.Empty : base.GetstringAsString(ColumnNames.NameEng);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameEng);
				else
					this.NameEng = base.SetstringAsString(ColumnNames.NameEng, value);
			}
		}

		public virtual string s_NameAr
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameAr) ? string.Empty : base.GetstringAsString(ColumnNames.NameAr);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameAr);
				else
					this.NameAr = base.SetstringAsString(ColumnNames.NameAr, value);
			}
		}

		public virtual string s_ImagePath
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ImagePath) ? string.Empty : base.GetstringAsString(ColumnNames.ImagePath);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ImagePath);
				else
					this.ImagePath = base.SetstringAsString(ColumnNames.ImagePath, value);
			}
		}

		public virtual string s_HoverImage
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.HoverImage) ? string.Empty : base.GetstringAsString(ColumnNames.HoverImage);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.HoverImage);
				else
					this.HoverImage = base.SetstringAsString(ColumnNames.HoverImage, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter TopLevelCatID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TopLevelCatID, Parameters.TopLevelCatID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameEng
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameEng, Parameters.NameEng);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameAr
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameAr, Parameters.NameAr);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ImagePath
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ImagePath, Parameters.ImagePath);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter HoverImage
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.HoverImage, Parameters.HoverImage);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter TopLevelCatID
		    {
				get
		        {
					if(_TopLevelCatID_W == null)
	        	    {
						_TopLevelCatID_W = TearOff.TopLevelCatID;
					}
					return _TopLevelCatID_W;
				}
			}

			public WhereParameter NameEng
		    {
				get
		        {
					if(_NameEng_W == null)
	        	    {
						_NameEng_W = TearOff.NameEng;
					}
					return _NameEng_W;
				}
			}

			public WhereParameter NameAr
		    {
				get
		        {
					if(_NameAr_W == null)
	        	    {
						_NameAr_W = TearOff.NameAr;
					}
					return _NameAr_W;
				}
			}

			public WhereParameter ImagePath
		    {
				get
		        {
					if(_ImagePath_W == null)
	        	    {
						_ImagePath_W = TearOff.ImagePath;
					}
					return _ImagePath_W;
				}
			}

			public WhereParameter HoverImage
		    {
				get
		        {
					if(_HoverImage_W == null)
	        	    {
						_HoverImage_W = TearOff.HoverImage;
					}
					return _HoverImage_W;
				}
			}

			private WhereParameter _TopLevelCatID_W = null;
			private WhereParameter _NameEng_W = null;
			private WhereParameter _NameAr_W = null;
			private WhereParameter _ImagePath_W = null;
			private WhereParameter _HoverImage_W = null;

			public void WhereClauseReset()
			{
				_TopLevelCatID_W = null;
				_NameEng_W = null;
				_NameAr_W = null;
				_ImagePath_W = null;
				_HoverImage_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter TopLevelCatID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TopLevelCatID, Parameters.TopLevelCatID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameEng
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameEng, Parameters.NameEng);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameAr
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameAr, Parameters.NameAr);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ImagePath
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ImagePath, Parameters.ImagePath);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter HoverImage
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.HoverImage, Parameters.HoverImage);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter TopLevelCatID
		    {
				get
		        {
					if(_TopLevelCatID_W == null)
	        	    {
						_TopLevelCatID_W = TearOff.TopLevelCatID;
					}
					return _TopLevelCatID_W;
				}
			}

			public AggregateParameter NameEng
		    {
				get
		        {
					if(_NameEng_W == null)
	        	    {
						_NameEng_W = TearOff.NameEng;
					}
					return _NameEng_W;
				}
			}

			public AggregateParameter NameAr
		    {
				get
		        {
					if(_NameAr_W == null)
	        	    {
						_NameAr_W = TearOff.NameAr;
					}
					return _NameAr_W;
				}
			}

			public AggregateParameter ImagePath
		    {
				get
		        {
					if(_ImagePath_W == null)
	        	    {
						_ImagePath_W = TearOff.ImagePath;
					}
					return _ImagePath_W;
				}
			}

			public AggregateParameter HoverImage
		    {
				get
		        {
					if(_HoverImage_W == null)
	        	    {
						_HoverImage_W = TearOff.HoverImage;
					}
					return _HoverImage_W;
				}
			}

			private AggregateParameter _TopLevelCatID_W = null;
			private AggregateParameter _NameEng_W = null;
			private AggregateParameter _NameAr_W = null;
			private AggregateParameter _ImagePath_W = null;
			private AggregateParameter _HoverImage_W = null;

			public void AggregateClauseReset()
			{
				_TopLevelCatID_W = null;
				_NameEng_W = null;
				_NameAr_W = null;
				_ImagePath_W = null;
				_HoverImage_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TopLevelCatInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.TopLevelCatID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TopLevelCatUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TopLevelCatDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.TopLevelCatID);
			p.SourceColumn = ColumnNames.TopLevelCatID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.TopLevelCatID);
			p.SourceColumn = ColumnNames.TopLevelCatID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameEng);
			p.SourceColumn = ColumnNames.NameEng;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameAr);
			p.SourceColumn = ColumnNames.NameAr;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ImagePath);
			p.SourceColumn = ColumnNames.ImagePath;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.HoverImage);
			p.SourceColumn = ColumnNames.HoverImage;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
