
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using ErmiaWS_DAL;
using System.Collections.Specialized;
using System.Data.SqlClient;
using System.Data;

namespace Ermia_BLL
{
	public class Categories : _Categories
	{
		public Categories()
		{
		
		}

        public virtual bool GetCategoriesByTypeID(int TypeID)
        {
            ListDictionary parameters = new ListDictionary();

            parameters.Add(new SqlParameter("@TypeID", SqlDbType.Int, 0), TypeID);

            return LoadFromSql("GetCategoriesByTypeID", parameters);

        }

        public virtual bool GetCategoriesByTypeIDAndPageID(int TypeID, int PageID)
        {
            ListDictionary parameters = new ListDictionary();

            parameters.Add(new SqlParameter("@TypeID", SqlDbType.Int, 0), TypeID);
            parameters.Add(new SqlParameter("@PageID", SqlDbType.Int, 0), PageID);

            return LoadFromSql("GetCategoriesByTypeIDAndPageID", parameters);

        }
	}
}
