
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using E3zmni.DAL;
namespace E3zmni.BLL
{
	public class CardColor : _CardColor
	{
		public CardColor()
		{
		
		}

        public virtual bool GetCardColorsByCardID(int CardID)
        {
            this.Where.CardID.Value = CardID;
            this.Where.CardID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            return this.Query.Load();

        }

        public virtual bool GetCardColorsByCardIDTop3(int CardID)
        {
            this.Where.CardID.Value = CardID;
            this.Where.CardID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            this.Query.Top = 3;
            return this.Query.Load();

        }
	}
}
