//tealium universal tag - utag.16 ut4.0.201209121754, Copyright 2012 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1};u.src='2612518';u.type='stayc388';u.cat='sgh_s484';u.found_type=false;u.found_cat=false;u.countertype='standard';u.qty=0;u.qsp_delim=';';u.kvp_delim='=';u.base_url='//fls.doubleclick.net/activityi;src='+u.src+';'
u.map={};u.extend=[];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!='undefined'){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};if(typeof utag.linkHandler=='undefined'){utag.linkHandler=function(a,b,c,d,e){if(!a){a=window.event;}
if(a.target){b=a.target;}else if(a.srcElement){b=a.srcElement;}
if(typeof b=="undefined"||typeof b.tagName=="undefined"){return;}
if(b.id=="go-sid"||b.id=="go-signup"){c=[];if(u.type)c.push('type='+u.type);for(d in utag.loader.GV(u.map)){if(typeof b[d]!='undefined'&&b[d]!=''){e=u.map[d].split(',');for(f=0;f<e.length;f++){c.push(e[f]+u.kvp_delim+encodeURIComponent(b[d]));if(e[f]=='cat')u.found_cat=true;if(e[f]=='type')u.found_type=true;}}}
if(!u.found_type&&u.type=='')c.push('type=');if(!u.found_cat)c.push('cat='+u.cat);if(b._corder){if(typeof b._cquan!='undefined'){for(f=0;f<b._cquan.length;f++){u.qty+=parseInt(b._cquan[f]);}};if(u.qty==0){u.qty=1};c.push('qty='+(u.qty));c.push('cost='+b._csubtotal);c.push('ord='+b._corder);}else if(u.countertype=='standard'){c.push('ord='+(Math.random()*10000000000000));}else if(u.countertype=='unique'){c.push('ord=1');c.push('num='+(Math.random()*10000000000000));}else{c.push('ord='+utag.data['cp.utag_main_ses_id']);}
d=document.createElement('iframe');d.setAttribute('id','utag_16_iframe');d.setAttribute('height','1');d.setAttribute('width','1');d.setAttribute('style','display:none');d.setAttribute('src',u.base_url+c.join(u.qsp_delim));document.body.appendChild(d);}}
utag.loader.EV(window,"mousedown",utag.linkHandler);}}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('16','luxottica.sunglasshut');}catch(e){}
