
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DAL
{
	public abstract class _RoomMember : SqlClientEntity
	{
		public _RoomMember()
		{
			this.QuerySource = "RoomMember";
			this.MappingName = "RoomMember";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_RoomMemberLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int MemberID, int RoomID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.MemberID, MemberID);

parameters.Add(Parameters.RoomID, RoomID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_RoomMemberLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter MemberID
			{
				get
				{
					return new SqlParameter("@MemberID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter RoomID
			{
				get
				{
					return new SqlParameter("@RoomID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter HasMic
			{
				get
				{
					return new SqlParameter("@HasMic", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter HasCam
			{
				get
				{
					return new SqlParameter("@HasCam", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter CanAccessMic
			{
				get
				{
					return new SqlParameter("@CanAccessMic", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter CanAccessCam
			{
				get
				{
					return new SqlParameter("@CanAccessCam", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter CanWrite
			{
				get
				{
					return new SqlParameter("@CanWrite", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsMarked
			{
				get
				{
					return new SqlParameter("@IsMarked", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter AskForMic
			{
				get
				{
					return new SqlParameter("@AskForMic", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter QueueOrder
			{
				get
				{
					return new SqlParameter("@QueueOrder", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter UserRate
			{
				get
				{
					return new SqlParameter("@UserRate", SqlDbType.SmallInt, 0);
				}
			}
			
			public static SqlParameter InRoom
			{
				get
				{
					return new SqlParameter("@InRoom", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter RoomMemberLevelID
			{
				get
				{
					return new SqlParameter("@RoomMemberLevelID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter NotifyOnFriendsLogOn
			{
				get
				{
					return new SqlParameter("@NotifyOnFriendsLogOn", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter NotifyOnFriendsLogOff
			{
				get
				{
					return new SqlParameter("@NotifyOnFriendsLogOff", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter NotifyOnMicOn
			{
				get
				{
					return new SqlParameter("@NotifyOnMicOn", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter NotifyOnMicOff
			{
				get
				{
					return new SqlParameter("@NotifyOnMicOff", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter NotifyOnOpenCam
			{
				get
				{
					return new SqlParameter("@NotifyOnOpenCam", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter NotifyOnCloseCam
			{
				get
				{
					return new SqlParameter("@NotifyOnCloseCam", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsFavorite
			{
				get
				{
					return new SqlParameter("@IsFavorite", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter ShowMessageTime
			{
				get
				{
					return new SqlParameter("@ShowMessageTime", SqlDbType.Bit, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string MemberID = "MemberID";
            public const string RoomID = "RoomID";
            public const string HasMic = "HasMic";
            public const string HasCam = "HasCam";
            public const string CanAccessMic = "CanAccessMic";
            public const string CanAccessCam = "CanAccessCam";
            public const string CanWrite = "CanWrite";
            public const string IsMarked = "IsMarked";
            public const string AskForMic = "AskForMic";
            public const string QueueOrder = "QueueOrder";
            public const string UserRate = "UserRate";
            public const string InRoom = "InRoom";
            public const string RoomMemberLevelID = "RoomMemberLevelID";
            public const string NotifyOnFriendsLogOn = "NotifyOnFriendsLogOn";
            public const string NotifyOnFriendsLogOff = "NotifyOnFriendsLogOff";
            public const string NotifyOnMicOn = "NotifyOnMicOn";
            public const string NotifyOnMicOff = "NotifyOnMicOff";
            public const string NotifyOnOpenCam = "NotifyOnOpenCam";
            public const string NotifyOnCloseCam = "NotifyOnCloseCam";
            public const string IsFavorite = "IsFavorite";
            public const string ShowMessageTime = "ShowMessageTime";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[MemberID] = _RoomMember.PropertyNames.MemberID;
					ht[RoomID] = _RoomMember.PropertyNames.RoomID;
					ht[HasMic] = _RoomMember.PropertyNames.HasMic;
					ht[HasCam] = _RoomMember.PropertyNames.HasCam;
					ht[CanAccessMic] = _RoomMember.PropertyNames.CanAccessMic;
					ht[CanAccessCam] = _RoomMember.PropertyNames.CanAccessCam;
					ht[CanWrite] = _RoomMember.PropertyNames.CanWrite;
					ht[IsMarked] = _RoomMember.PropertyNames.IsMarked;
					ht[AskForMic] = _RoomMember.PropertyNames.AskForMic;
					ht[QueueOrder] = _RoomMember.PropertyNames.QueueOrder;
					ht[UserRate] = _RoomMember.PropertyNames.UserRate;
					ht[InRoom] = _RoomMember.PropertyNames.InRoom;
					ht[RoomMemberLevelID] = _RoomMember.PropertyNames.RoomMemberLevelID;
					ht[NotifyOnFriendsLogOn] = _RoomMember.PropertyNames.NotifyOnFriendsLogOn;
					ht[NotifyOnFriendsLogOff] = _RoomMember.PropertyNames.NotifyOnFriendsLogOff;
					ht[NotifyOnMicOn] = _RoomMember.PropertyNames.NotifyOnMicOn;
					ht[NotifyOnMicOff] = _RoomMember.PropertyNames.NotifyOnMicOff;
					ht[NotifyOnOpenCam] = _RoomMember.PropertyNames.NotifyOnOpenCam;
					ht[NotifyOnCloseCam] = _RoomMember.PropertyNames.NotifyOnCloseCam;
					ht[IsFavorite] = _RoomMember.PropertyNames.IsFavorite;
					ht[ShowMessageTime] = _RoomMember.PropertyNames.ShowMessageTime;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string MemberID = "MemberID";
            public const string RoomID = "RoomID";
            public const string HasMic = "HasMic";
            public const string HasCam = "HasCam";
            public const string CanAccessMic = "CanAccessMic";
            public const string CanAccessCam = "CanAccessCam";
            public const string CanWrite = "CanWrite";
            public const string IsMarked = "IsMarked";
            public const string AskForMic = "AskForMic";
            public const string QueueOrder = "QueueOrder";
            public const string UserRate = "UserRate";
            public const string InRoom = "InRoom";
            public const string RoomMemberLevelID = "RoomMemberLevelID";
            public const string NotifyOnFriendsLogOn = "NotifyOnFriendsLogOn";
            public const string NotifyOnFriendsLogOff = "NotifyOnFriendsLogOff";
            public const string NotifyOnMicOn = "NotifyOnMicOn";
            public const string NotifyOnMicOff = "NotifyOnMicOff";
            public const string NotifyOnOpenCam = "NotifyOnOpenCam";
            public const string NotifyOnCloseCam = "NotifyOnCloseCam";
            public const string IsFavorite = "IsFavorite";
            public const string ShowMessageTime = "ShowMessageTime";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[MemberID] = _RoomMember.ColumnNames.MemberID;
					ht[RoomID] = _RoomMember.ColumnNames.RoomID;
					ht[HasMic] = _RoomMember.ColumnNames.HasMic;
					ht[HasCam] = _RoomMember.ColumnNames.HasCam;
					ht[CanAccessMic] = _RoomMember.ColumnNames.CanAccessMic;
					ht[CanAccessCam] = _RoomMember.ColumnNames.CanAccessCam;
					ht[CanWrite] = _RoomMember.ColumnNames.CanWrite;
					ht[IsMarked] = _RoomMember.ColumnNames.IsMarked;
					ht[AskForMic] = _RoomMember.ColumnNames.AskForMic;
					ht[QueueOrder] = _RoomMember.ColumnNames.QueueOrder;
					ht[UserRate] = _RoomMember.ColumnNames.UserRate;
					ht[InRoom] = _RoomMember.ColumnNames.InRoom;
					ht[RoomMemberLevelID] = _RoomMember.ColumnNames.RoomMemberLevelID;
					ht[NotifyOnFriendsLogOn] = _RoomMember.ColumnNames.NotifyOnFriendsLogOn;
					ht[NotifyOnFriendsLogOff] = _RoomMember.ColumnNames.NotifyOnFriendsLogOff;
					ht[NotifyOnMicOn] = _RoomMember.ColumnNames.NotifyOnMicOn;
					ht[NotifyOnMicOff] = _RoomMember.ColumnNames.NotifyOnMicOff;
					ht[NotifyOnOpenCam] = _RoomMember.ColumnNames.NotifyOnOpenCam;
					ht[NotifyOnCloseCam] = _RoomMember.ColumnNames.NotifyOnCloseCam;
					ht[IsFavorite] = _RoomMember.ColumnNames.IsFavorite;
					ht[ShowMessageTime] = _RoomMember.ColumnNames.ShowMessageTime;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string MemberID = "s_MemberID";
            public const string RoomID = "s_RoomID";
            public const string HasMic = "s_HasMic";
            public const string HasCam = "s_HasCam";
            public const string CanAccessMic = "s_CanAccessMic";
            public const string CanAccessCam = "s_CanAccessCam";
            public const string CanWrite = "s_CanWrite";
            public const string IsMarked = "s_IsMarked";
            public const string AskForMic = "s_AskForMic";
            public const string QueueOrder = "s_QueueOrder";
            public const string UserRate = "s_UserRate";
            public const string InRoom = "s_InRoom";
            public const string RoomMemberLevelID = "s_RoomMemberLevelID";
            public const string NotifyOnFriendsLogOn = "s_NotifyOnFriendsLogOn";
            public const string NotifyOnFriendsLogOff = "s_NotifyOnFriendsLogOff";
            public const string NotifyOnMicOn = "s_NotifyOnMicOn";
            public const string NotifyOnMicOff = "s_NotifyOnMicOff";
            public const string NotifyOnOpenCam = "s_NotifyOnOpenCam";
            public const string NotifyOnCloseCam = "s_NotifyOnCloseCam";
            public const string IsFavorite = "s_IsFavorite";
            public const string ShowMessageTime = "s_ShowMessageTime";

		}
		#endregion		
		
		#region Properties
	
		public virtual int MemberID
	    {
			get
	        {
				return base.Getint(ColumnNames.MemberID);
			}
			set
	        {
				base.Setint(ColumnNames.MemberID, value);
			}
		}

		public virtual int RoomID
	    {
			get
	        {
				return base.Getint(ColumnNames.RoomID);
			}
			set
	        {
				base.Setint(ColumnNames.RoomID, value);
			}
		}

		public virtual bool HasMic
	    {
			get
	        {
				return base.Getbool(ColumnNames.HasMic);
			}
			set
	        {
				base.Setbool(ColumnNames.HasMic, value);
			}
		}

		public virtual bool HasCam
	    {
			get
	        {
				return base.Getbool(ColumnNames.HasCam);
			}
			set
	        {
				base.Setbool(ColumnNames.HasCam, value);
			}
		}

		public virtual bool CanAccessMic
	    {
			get
	        {
				return base.Getbool(ColumnNames.CanAccessMic);
			}
			set
	        {
				base.Setbool(ColumnNames.CanAccessMic, value);
			}
		}

		public virtual bool CanAccessCam
	    {
			get
	        {
				return base.Getbool(ColumnNames.CanAccessCam);
			}
			set
	        {
				base.Setbool(ColumnNames.CanAccessCam, value);
			}
		}

		public virtual bool CanWrite
	    {
			get
	        {
				return base.Getbool(ColumnNames.CanWrite);
			}
			set
	        {
				base.Setbool(ColumnNames.CanWrite, value);
			}
		}

		public virtual bool IsMarked
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsMarked);
			}
			set
	        {
				base.Setbool(ColumnNames.IsMarked, value);
			}
		}

		public virtual bool AskForMic
	    {
			get
	        {
				return base.Getbool(ColumnNames.AskForMic);
			}
			set
	        {
				base.Setbool(ColumnNames.AskForMic, value);
			}
		}

		public virtual int QueueOrder
	    {
			get
	        {
				return base.Getint(ColumnNames.QueueOrder);
			}
			set
	        {
				base.Setint(ColumnNames.QueueOrder, value);
			}
		}

		public virtual short UserRate
	    {
			get
	        {
				return base.Getshort(ColumnNames.UserRate);
			}
			set
	        {
				base.Setshort(ColumnNames.UserRate, value);
			}
		}

		public virtual bool InRoom
	    {
			get
	        {
				return base.Getbool(ColumnNames.InRoom);
			}
			set
	        {
				base.Setbool(ColumnNames.InRoom, value);
			}
		}

		public virtual int RoomMemberLevelID
	    {
			get
	        {
				return base.Getint(ColumnNames.RoomMemberLevelID);
			}
			set
	        {
				base.Setint(ColumnNames.RoomMemberLevelID, value);
			}
		}

		public virtual bool NotifyOnFriendsLogOn
	    {
			get
	        {
				return base.Getbool(ColumnNames.NotifyOnFriendsLogOn);
			}
			set
	        {
				base.Setbool(ColumnNames.NotifyOnFriendsLogOn, value);
			}
		}

		public virtual bool NotifyOnFriendsLogOff
	    {
			get
	        {
				return base.Getbool(ColumnNames.NotifyOnFriendsLogOff);
			}
			set
	        {
				base.Setbool(ColumnNames.NotifyOnFriendsLogOff, value);
			}
		}

		public virtual bool NotifyOnMicOn
	    {
			get
	        {
				return base.Getbool(ColumnNames.NotifyOnMicOn);
			}
			set
	        {
				base.Setbool(ColumnNames.NotifyOnMicOn, value);
			}
		}

		public virtual bool NotifyOnMicOff
	    {
			get
	        {
				return base.Getbool(ColumnNames.NotifyOnMicOff);
			}
			set
	        {
				base.Setbool(ColumnNames.NotifyOnMicOff, value);
			}
		}

		public virtual bool NotifyOnOpenCam
	    {
			get
	        {
				return base.Getbool(ColumnNames.NotifyOnOpenCam);
			}
			set
	        {
				base.Setbool(ColumnNames.NotifyOnOpenCam, value);
			}
		}

		public virtual bool NotifyOnCloseCam
	    {
			get
	        {
				return base.Getbool(ColumnNames.NotifyOnCloseCam);
			}
			set
	        {
				base.Setbool(ColumnNames.NotifyOnCloseCam, value);
			}
		}

		public virtual bool IsFavorite
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsFavorite);
			}
			set
	        {
				base.Setbool(ColumnNames.IsFavorite, value);
			}
		}

		public virtual bool ShowMessageTime
	    {
			get
	        {
				return base.Getbool(ColumnNames.ShowMessageTime);
			}
			set
	        {
				base.Setbool(ColumnNames.ShowMessageTime, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_MemberID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MemberID) ? string.Empty : base.GetintAsString(ColumnNames.MemberID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MemberID);
				else
					this.MemberID = base.SetintAsString(ColumnNames.MemberID, value);
			}
		}

		public virtual string s_RoomID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RoomID) ? string.Empty : base.GetintAsString(ColumnNames.RoomID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RoomID);
				else
					this.RoomID = base.SetintAsString(ColumnNames.RoomID, value);
			}
		}

		public virtual string s_HasMic
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.HasMic) ? string.Empty : base.GetboolAsString(ColumnNames.HasMic);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.HasMic);
				else
					this.HasMic = base.SetboolAsString(ColumnNames.HasMic, value);
			}
		}

		public virtual string s_HasCam
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.HasCam) ? string.Empty : base.GetboolAsString(ColumnNames.HasCam);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.HasCam);
				else
					this.HasCam = base.SetboolAsString(ColumnNames.HasCam, value);
			}
		}

		public virtual string s_CanAccessMic
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CanAccessMic) ? string.Empty : base.GetboolAsString(ColumnNames.CanAccessMic);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CanAccessMic);
				else
					this.CanAccessMic = base.SetboolAsString(ColumnNames.CanAccessMic, value);
			}
		}

		public virtual string s_CanAccessCam
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CanAccessCam) ? string.Empty : base.GetboolAsString(ColumnNames.CanAccessCam);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CanAccessCam);
				else
					this.CanAccessCam = base.SetboolAsString(ColumnNames.CanAccessCam, value);
			}
		}

		public virtual string s_CanWrite
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CanWrite) ? string.Empty : base.GetboolAsString(ColumnNames.CanWrite);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CanWrite);
				else
					this.CanWrite = base.SetboolAsString(ColumnNames.CanWrite, value);
			}
		}

		public virtual string s_IsMarked
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsMarked) ? string.Empty : base.GetboolAsString(ColumnNames.IsMarked);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsMarked);
				else
					this.IsMarked = base.SetboolAsString(ColumnNames.IsMarked, value);
			}
		}

		public virtual string s_AskForMic
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AskForMic) ? string.Empty : base.GetboolAsString(ColumnNames.AskForMic);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AskForMic);
				else
					this.AskForMic = base.SetboolAsString(ColumnNames.AskForMic, value);
			}
		}

		public virtual string s_QueueOrder
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.QueueOrder) ? string.Empty : base.GetintAsString(ColumnNames.QueueOrder);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.QueueOrder);
				else
					this.QueueOrder = base.SetintAsString(ColumnNames.QueueOrder, value);
			}
		}

		public virtual string s_UserRate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UserRate) ? string.Empty : base.GetshortAsString(ColumnNames.UserRate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UserRate);
				else
					this.UserRate = base.SetshortAsString(ColumnNames.UserRate, value);
			}
		}

		public virtual string s_InRoom
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.InRoom) ? string.Empty : base.GetboolAsString(ColumnNames.InRoom);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.InRoom);
				else
					this.InRoom = base.SetboolAsString(ColumnNames.InRoom, value);
			}
		}

		public virtual string s_RoomMemberLevelID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RoomMemberLevelID) ? string.Empty : base.GetintAsString(ColumnNames.RoomMemberLevelID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RoomMemberLevelID);
				else
					this.RoomMemberLevelID = base.SetintAsString(ColumnNames.RoomMemberLevelID, value);
			}
		}

		public virtual string s_NotifyOnFriendsLogOn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NotifyOnFriendsLogOn) ? string.Empty : base.GetboolAsString(ColumnNames.NotifyOnFriendsLogOn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NotifyOnFriendsLogOn);
				else
					this.NotifyOnFriendsLogOn = base.SetboolAsString(ColumnNames.NotifyOnFriendsLogOn, value);
			}
		}

		public virtual string s_NotifyOnFriendsLogOff
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NotifyOnFriendsLogOff) ? string.Empty : base.GetboolAsString(ColumnNames.NotifyOnFriendsLogOff);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NotifyOnFriendsLogOff);
				else
					this.NotifyOnFriendsLogOff = base.SetboolAsString(ColumnNames.NotifyOnFriendsLogOff, value);
			}
		}

		public virtual string s_NotifyOnMicOn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NotifyOnMicOn) ? string.Empty : base.GetboolAsString(ColumnNames.NotifyOnMicOn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NotifyOnMicOn);
				else
					this.NotifyOnMicOn = base.SetboolAsString(ColumnNames.NotifyOnMicOn, value);
			}
		}

		public virtual string s_NotifyOnMicOff
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NotifyOnMicOff) ? string.Empty : base.GetboolAsString(ColumnNames.NotifyOnMicOff);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NotifyOnMicOff);
				else
					this.NotifyOnMicOff = base.SetboolAsString(ColumnNames.NotifyOnMicOff, value);
			}
		}

		public virtual string s_NotifyOnOpenCam
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NotifyOnOpenCam) ? string.Empty : base.GetboolAsString(ColumnNames.NotifyOnOpenCam);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NotifyOnOpenCam);
				else
					this.NotifyOnOpenCam = base.SetboolAsString(ColumnNames.NotifyOnOpenCam, value);
			}
		}

		public virtual string s_NotifyOnCloseCam
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NotifyOnCloseCam) ? string.Empty : base.GetboolAsString(ColumnNames.NotifyOnCloseCam);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NotifyOnCloseCam);
				else
					this.NotifyOnCloseCam = base.SetboolAsString(ColumnNames.NotifyOnCloseCam, value);
			}
		}

		public virtual string s_IsFavorite
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsFavorite) ? string.Empty : base.GetboolAsString(ColumnNames.IsFavorite);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsFavorite);
				else
					this.IsFavorite = base.SetboolAsString(ColumnNames.IsFavorite, value);
			}
		}

		public virtual string s_ShowMessageTime
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ShowMessageTime) ? string.Empty : base.GetboolAsString(ColumnNames.ShowMessageTime);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ShowMessageTime);
				else
					this.ShowMessageTime = base.SetboolAsString(ColumnNames.ShowMessageTime, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter MemberID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MemberID, Parameters.MemberID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RoomID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RoomID, Parameters.RoomID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter HasMic
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.HasMic, Parameters.HasMic);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter HasCam
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.HasCam, Parameters.HasCam);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CanAccessMic
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CanAccessMic, Parameters.CanAccessMic);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CanAccessCam
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CanAccessCam, Parameters.CanAccessCam);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CanWrite
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CanWrite, Parameters.CanWrite);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsMarked
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsMarked, Parameters.IsMarked);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AskForMic
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AskForMic, Parameters.AskForMic);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter QueueOrder
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.QueueOrder, Parameters.QueueOrder);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UserRate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UserRate, Parameters.UserRate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter InRoom
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.InRoom, Parameters.InRoom);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RoomMemberLevelID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RoomMemberLevelID, Parameters.RoomMemberLevelID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NotifyOnFriendsLogOn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NotifyOnFriendsLogOn, Parameters.NotifyOnFriendsLogOn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NotifyOnFriendsLogOff
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NotifyOnFriendsLogOff, Parameters.NotifyOnFriendsLogOff);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NotifyOnMicOn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NotifyOnMicOn, Parameters.NotifyOnMicOn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NotifyOnMicOff
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NotifyOnMicOff, Parameters.NotifyOnMicOff);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NotifyOnOpenCam
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NotifyOnOpenCam, Parameters.NotifyOnOpenCam);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NotifyOnCloseCam
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NotifyOnCloseCam, Parameters.NotifyOnCloseCam);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsFavorite
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsFavorite, Parameters.IsFavorite);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ShowMessageTime
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ShowMessageTime, Parameters.ShowMessageTime);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter MemberID
		    {
				get
		        {
					if(_MemberID_W == null)
	        	    {
						_MemberID_W = TearOff.MemberID;
					}
					return _MemberID_W;
				}
			}

			public WhereParameter RoomID
		    {
				get
		        {
					if(_RoomID_W == null)
	        	    {
						_RoomID_W = TearOff.RoomID;
					}
					return _RoomID_W;
				}
			}

			public WhereParameter HasMic
		    {
				get
		        {
					if(_HasMic_W == null)
	        	    {
						_HasMic_W = TearOff.HasMic;
					}
					return _HasMic_W;
				}
			}

			public WhereParameter HasCam
		    {
				get
		        {
					if(_HasCam_W == null)
	        	    {
						_HasCam_W = TearOff.HasCam;
					}
					return _HasCam_W;
				}
			}

			public WhereParameter CanAccessMic
		    {
				get
		        {
					if(_CanAccessMic_W == null)
	        	    {
						_CanAccessMic_W = TearOff.CanAccessMic;
					}
					return _CanAccessMic_W;
				}
			}

			public WhereParameter CanAccessCam
		    {
				get
		        {
					if(_CanAccessCam_W == null)
	        	    {
						_CanAccessCam_W = TearOff.CanAccessCam;
					}
					return _CanAccessCam_W;
				}
			}

			public WhereParameter CanWrite
		    {
				get
		        {
					if(_CanWrite_W == null)
	        	    {
						_CanWrite_W = TearOff.CanWrite;
					}
					return _CanWrite_W;
				}
			}

			public WhereParameter IsMarked
		    {
				get
		        {
					if(_IsMarked_W == null)
	        	    {
						_IsMarked_W = TearOff.IsMarked;
					}
					return _IsMarked_W;
				}
			}

			public WhereParameter AskForMic
		    {
				get
		        {
					if(_AskForMic_W == null)
	        	    {
						_AskForMic_W = TearOff.AskForMic;
					}
					return _AskForMic_W;
				}
			}

			public WhereParameter QueueOrder
		    {
				get
		        {
					if(_QueueOrder_W == null)
	        	    {
						_QueueOrder_W = TearOff.QueueOrder;
					}
					return _QueueOrder_W;
				}
			}

			public WhereParameter UserRate
		    {
				get
		        {
					if(_UserRate_W == null)
	        	    {
						_UserRate_W = TearOff.UserRate;
					}
					return _UserRate_W;
				}
			}

			public WhereParameter InRoom
		    {
				get
		        {
					if(_InRoom_W == null)
	        	    {
						_InRoom_W = TearOff.InRoom;
					}
					return _InRoom_W;
				}
			}

			public WhereParameter RoomMemberLevelID
		    {
				get
		        {
					if(_RoomMemberLevelID_W == null)
	        	    {
						_RoomMemberLevelID_W = TearOff.RoomMemberLevelID;
					}
					return _RoomMemberLevelID_W;
				}
			}

			public WhereParameter NotifyOnFriendsLogOn
		    {
				get
		        {
					if(_NotifyOnFriendsLogOn_W == null)
	        	    {
						_NotifyOnFriendsLogOn_W = TearOff.NotifyOnFriendsLogOn;
					}
					return _NotifyOnFriendsLogOn_W;
				}
			}

			public WhereParameter NotifyOnFriendsLogOff
		    {
				get
		        {
					if(_NotifyOnFriendsLogOff_W == null)
	        	    {
						_NotifyOnFriendsLogOff_W = TearOff.NotifyOnFriendsLogOff;
					}
					return _NotifyOnFriendsLogOff_W;
				}
			}

			public WhereParameter NotifyOnMicOn
		    {
				get
		        {
					if(_NotifyOnMicOn_W == null)
	        	    {
						_NotifyOnMicOn_W = TearOff.NotifyOnMicOn;
					}
					return _NotifyOnMicOn_W;
				}
			}

			public WhereParameter NotifyOnMicOff
		    {
				get
		        {
					if(_NotifyOnMicOff_W == null)
	        	    {
						_NotifyOnMicOff_W = TearOff.NotifyOnMicOff;
					}
					return _NotifyOnMicOff_W;
				}
			}

			public WhereParameter NotifyOnOpenCam
		    {
				get
		        {
					if(_NotifyOnOpenCam_W == null)
	        	    {
						_NotifyOnOpenCam_W = TearOff.NotifyOnOpenCam;
					}
					return _NotifyOnOpenCam_W;
				}
			}

			public WhereParameter NotifyOnCloseCam
		    {
				get
		        {
					if(_NotifyOnCloseCam_W == null)
	        	    {
						_NotifyOnCloseCam_W = TearOff.NotifyOnCloseCam;
					}
					return _NotifyOnCloseCam_W;
				}
			}

			public WhereParameter IsFavorite
		    {
				get
		        {
					if(_IsFavorite_W == null)
	        	    {
						_IsFavorite_W = TearOff.IsFavorite;
					}
					return _IsFavorite_W;
				}
			}

			public WhereParameter ShowMessageTime
		    {
				get
		        {
					if(_ShowMessageTime_W == null)
	        	    {
						_ShowMessageTime_W = TearOff.ShowMessageTime;
					}
					return _ShowMessageTime_W;
				}
			}

			private WhereParameter _MemberID_W = null;
			private WhereParameter _RoomID_W = null;
			private WhereParameter _HasMic_W = null;
			private WhereParameter _HasCam_W = null;
			private WhereParameter _CanAccessMic_W = null;
			private WhereParameter _CanAccessCam_W = null;
			private WhereParameter _CanWrite_W = null;
			private WhereParameter _IsMarked_W = null;
			private WhereParameter _AskForMic_W = null;
			private WhereParameter _QueueOrder_W = null;
			private WhereParameter _UserRate_W = null;
			private WhereParameter _InRoom_W = null;
			private WhereParameter _RoomMemberLevelID_W = null;
			private WhereParameter _NotifyOnFriendsLogOn_W = null;
			private WhereParameter _NotifyOnFriendsLogOff_W = null;
			private WhereParameter _NotifyOnMicOn_W = null;
			private WhereParameter _NotifyOnMicOff_W = null;
			private WhereParameter _NotifyOnOpenCam_W = null;
			private WhereParameter _NotifyOnCloseCam_W = null;
			private WhereParameter _IsFavorite_W = null;
			private WhereParameter _ShowMessageTime_W = null;

			public void WhereClauseReset()
			{
				_MemberID_W = null;
				_RoomID_W = null;
				_HasMic_W = null;
				_HasCam_W = null;
				_CanAccessMic_W = null;
				_CanAccessCam_W = null;
				_CanWrite_W = null;
				_IsMarked_W = null;
				_AskForMic_W = null;
				_QueueOrder_W = null;
				_UserRate_W = null;
				_InRoom_W = null;
				_RoomMemberLevelID_W = null;
				_NotifyOnFriendsLogOn_W = null;
				_NotifyOnFriendsLogOff_W = null;
				_NotifyOnMicOn_W = null;
				_NotifyOnMicOff_W = null;
				_NotifyOnOpenCam_W = null;
				_NotifyOnCloseCam_W = null;
				_IsFavorite_W = null;
				_ShowMessageTime_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter MemberID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MemberID, Parameters.MemberID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RoomID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RoomID, Parameters.RoomID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter HasMic
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.HasMic, Parameters.HasMic);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter HasCam
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.HasCam, Parameters.HasCam);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CanAccessMic
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CanAccessMic, Parameters.CanAccessMic);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CanAccessCam
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CanAccessCam, Parameters.CanAccessCam);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CanWrite
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CanWrite, Parameters.CanWrite);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsMarked
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsMarked, Parameters.IsMarked);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AskForMic
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AskForMic, Parameters.AskForMic);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter QueueOrder
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.QueueOrder, Parameters.QueueOrder);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UserRate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UserRate, Parameters.UserRate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter InRoom
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.InRoom, Parameters.InRoom);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RoomMemberLevelID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RoomMemberLevelID, Parameters.RoomMemberLevelID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NotifyOnFriendsLogOn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NotifyOnFriendsLogOn, Parameters.NotifyOnFriendsLogOn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NotifyOnFriendsLogOff
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NotifyOnFriendsLogOff, Parameters.NotifyOnFriendsLogOff);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NotifyOnMicOn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NotifyOnMicOn, Parameters.NotifyOnMicOn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NotifyOnMicOff
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NotifyOnMicOff, Parameters.NotifyOnMicOff);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NotifyOnOpenCam
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NotifyOnOpenCam, Parameters.NotifyOnOpenCam);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NotifyOnCloseCam
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NotifyOnCloseCam, Parameters.NotifyOnCloseCam);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsFavorite
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsFavorite, Parameters.IsFavorite);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ShowMessageTime
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ShowMessageTime, Parameters.ShowMessageTime);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter MemberID
		    {
				get
		        {
					if(_MemberID_W == null)
	        	    {
						_MemberID_W = TearOff.MemberID;
					}
					return _MemberID_W;
				}
			}

			public AggregateParameter RoomID
		    {
				get
		        {
					if(_RoomID_W == null)
	        	    {
						_RoomID_W = TearOff.RoomID;
					}
					return _RoomID_W;
				}
			}

			public AggregateParameter HasMic
		    {
				get
		        {
					if(_HasMic_W == null)
	        	    {
						_HasMic_W = TearOff.HasMic;
					}
					return _HasMic_W;
				}
			}

			public AggregateParameter HasCam
		    {
				get
		        {
					if(_HasCam_W == null)
	        	    {
						_HasCam_W = TearOff.HasCam;
					}
					return _HasCam_W;
				}
			}

			public AggregateParameter CanAccessMic
		    {
				get
		        {
					if(_CanAccessMic_W == null)
	        	    {
						_CanAccessMic_W = TearOff.CanAccessMic;
					}
					return _CanAccessMic_W;
				}
			}

			public AggregateParameter CanAccessCam
		    {
				get
		        {
					if(_CanAccessCam_W == null)
	        	    {
						_CanAccessCam_W = TearOff.CanAccessCam;
					}
					return _CanAccessCam_W;
				}
			}

			public AggregateParameter CanWrite
		    {
				get
		        {
					if(_CanWrite_W == null)
	        	    {
						_CanWrite_W = TearOff.CanWrite;
					}
					return _CanWrite_W;
				}
			}

			public AggregateParameter IsMarked
		    {
				get
		        {
					if(_IsMarked_W == null)
	        	    {
						_IsMarked_W = TearOff.IsMarked;
					}
					return _IsMarked_W;
				}
			}

			public AggregateParameter AskForMic
		    {
				get
		        {
					if(_AskForMic_W == null)
	        	    {
						_AskForMic_W = TearOff.AskForMic;
					}
					return _AskForMic_W;
				}
			}

			public AggregateParameter QueueOrder
		    {
				get
		        {
					if(_QueueOrder_W == null)
	        	    {
						_QueueOrder_W = TearOff.QueueOrder;
					}
					return _QueueOrder_W;
				}
			}

			public AggregateParameter UserRate
		    {
				get
		        {
					if(_UserRate_W == null)
	        	    {
						_UserRate_W = TearOff.UserRate;
					}
					return _UserRate_W;
				}
			}

			public AggregateParameter InRoom
		    {
				get
		        {
					if(_InRoom_W == null)
	        	    {
						_InRoom_W = TearOff.InRoom;
					}
					return _InRoom_W;
				}
			}

			public AggregateParameter RoomMemberLevelID
		    {
				get
		        {
					if(_RoomMemberLevelID_W == null)
	        	    {
						_RoomMemberLevelID_W = TearOff.RoomMemberLevelID;
					}
					return _RoomMemberLevelID_W;
				}
			}

			public AggregateParameter NotifyOnFriendsLogOn
		    {
				get
		        {
					if(_NotifyOnFriendsLogOn_W == null)
	        	    {
						_NotifyOnFriendsLogOn_W = TearOff.NotifyOnFriendsLogOn;
					}
					return _NotifyOnFriendsLogOn_W;
				}
			}

			public AggregateParameter NotifyOnFriendsLogOff
		    {
				get
		        {
					if(_NotifyOnFriendsLogOff_W == null)
	        	    {
						_NotifyOnFriendsLogOff_W = TearOff.NotifyOnFriendsLogOff;
					}
					return _NotifyOnFriendsLogOff_W;
				}
			}

			public AggregateParameter NotifyOnMicOn
		    {
				get
		        {
					if(_NotifyOnMicOn_W == null)
	        	    {
						_NotifyOnMicOn_W = TearOff.NotifyOnMicOn;
					}
					return _NotifyOnMicOn_W;
				}
			}

			public AggregateParameter NotifyOnMicOff
		    {
				get
		        {
					if(_NotifyOnMicOff_W == null)
	        	    {
						_NotifyOnMicOff_W = TearOff.NotifyOnMicOff;
					}
					return _NotifyOnMicOff_W;
				}
			}

			public AggregateParameter NotifyOnOpenCam
		    {
				get
		        {
					if(_NotifyOnOpenCam_W == null)
	        	    {
						_NotifyOnOpenCam_W = TearOff.NotifyOnOpenCam;
					}
					return _NotifyOnOpenCam_W;
				}
			}

			public AggregateParameter NotifyOnCloseCam
		    {
				get
		        {
					if(_NotifyOnCloseCam_W == null)
	        	    {
						_NotifyOnCloseCam_W = TearOff.NotifyOnCloseCam;
					}
					return _NotifyOnCloseCam_W;
				}
			}

			public AggregateParameter IsFavorite
		    {
				get
		        {
					if(_IsFavorite_W == null)
	        	    {
						_IsFavorite_W = TearOff.IsFavorite;
					}
					return _IsFavorite_W;
				}
			}

			public AggregateParameter ShowMessageTime
		    {
				get
		        {
					if(_ShowMessageTime_W == null)
	        	    {
						_ShowMessageTime_W = TearOff.ShowMessageTime;
					}
					return _ShowMessageTime_W;
				}
			}

			private AggregateParameter _MemberID_W = null;
			private AggregateParameter _RoomID_W = null;
			private AggregateParameter _HasMic_W = null;
			private AggregateParameter _HasCam_W = null;
			private AggregateParameter _CanAccessMic_W = null;
			private AggregateParameter _CanAccessCam_W = null;
			private AggregateParameter _CanWrite_W = null;
			private AggregateParameter _IsMarked_W = null;
			private AggregateParameter _AskForMic_W = null;
			private AggregateParameter _QueueOrder_W = null;
			private AggregateParameter _UserRate_W = null;
			private AggregateParameter _InRoom_W = null;
			private AggregateParameter _RoomMemberLevelID_W = null;
			private AggregateParameter _NotifyOnFriendsLogOn_W = null;
			private AggregateParameter _NotifyOnFriendsLogOff_W = null;
			private AggregateParameter _NotifyOnMicOn_W = null;
			private AggregateParameter _NotifyOnMicOff_W = null;
			private AggregateParameter _NotifyOnOpenCam_W = null;
			private AggregateParameter _NotifyOnCloseCam_W = null;
			private AggregateParameter _IsFavorite_W = null;
			private AggregateParameter _ShowMessageTime_W = null;

			public void AggregateClauseReset()
			{
				_MemberID_W = null;
				_RoomID_W = null;
				_HasMic_W = null;
				_HasCam_W = null;
				_CanAccessMic_W = null;
				_CanAccessCam_W = null;
				_CanWrite_W = null;
				_IsMarked_W = null;
				_AskForMic_W = null;
				_QueueOrder_W = null;
				_UserRate_W = null;
				_InRoom_W = null;
				_RoomMemberLevelID_W = null;
				_NotifyOnFriendsLogOn_W = null;
				_NotifyOnFriendsLogOff_W = null;
				_NotifyOnMicOn_W = null;
				_NotifyOnMicOff_W = null;
				_NotifyOnOpenCam_W = null;
				_NotifyOnCloseCam_W = null;
				_IsFavorite_W = null;
				_ShowMessageTime_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RoomMemberInsert]";
	
			CreateParameters(cmd);
			    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RoomMemberUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RoomMemberDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.MemberID);
			p.SourceColumn = ColumnNames.MemberID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RoomID);
			p.SourceColumn = ColumnNames.RoomID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.MemberID);
			p.SourceColumn = ColumnNames.MemberID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RoomID);
			p.SourceColumn = ColumnNames.RoomID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.HasMic);
			p.SourceColumn = ColumnNames.HasMic;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.HasCam);
			p.SourceColumn = ColumnNames.HasCam;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CanAccessMic);
			p.SourceColumn = ColumnNames.CanAccessMic;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CanAccessCam);
			p.SourceColumn = ColumnNames.CanAccessCam;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CanWrite);
			p.SourceColumn = ColumnNames.CanWrite;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsMarked);
			p.SourceColumn = ColumnNames.IsMarked;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AskForMic);
			p.SourceColumn = ColumnNames.AskForMic;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.QueueOrder);
			p.SourceColumn = ColumnNames.QueueOrder;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UserRate);
			p.SourceColumn = ColumnNames.UserRate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.InRoom);
			p.SourceColumn = ColumnNames.InRoom;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RoomMemberLevelID);
			p.SourceColumn = ColumnNames.RoomMemberLevelID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NotifyOnFriendsLogOn);
			p.SourceColumn = ColumnNames.NotifyOnFriendsLogOn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NotifyOnFriendsLogOff);
			p.SourceColumn = ColumnNames.NotifyOnFriendsLogOff;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NotifyOnMicOn);
			p.SourceColumn = ColumnNames.NotifyOnMicOn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NotifyOnMicOff);
			p.SourceColumn = ColumnNames.NotifyOnMicOff;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NotifyOnOpenCam);
			p.SourceColumn = ColumnNames.NotifyOnOpenCam;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NotifyOnCloseCam);
			p.SourceColumn = ColumnNames.NotifyOnCloseCam;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsFavorite);
			p.SourceColumn = ColumnNames.IsFavorite;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ShowMessageTime);
			p.SourceColumn = ColumnNames.ShowMessageTime;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
