
// Generated by MyGeneration Version # (1.3.0.3)

using System;

namespace TouchMediaGUI
{
	public class DesignservicesType : _DesignservicesType
	{
		public DesignservicesType()
		{
		
		}
	}
}
