
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using TerryOptics.DAL;

namespace TerryOptics.BLL
{
	public class FeatureTypes : _FeatureTypes
	{
		public FeatureTypes()
		{
		
		}
	}
}
