
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GlobalLogistics.DAL;

namespace GlobalLogistics.BLL
{
	public class ShippingLines : _ShippingLines
	{
		public ShippingLines()
		{
		
		}
	}
}
